version: "3.8"

services:
  database:
    container_name: "postgres-dev-user-report"
    image: postgres:16.0-alpine3.18
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
    volumes:
      - user_volume_data:/var/lib/postgresql/data

volumes:
  user_volume_data:
